

server {
    listen 80;
    server_name srv459993.hstgr.cloud;

    location = / {
        return 301 /budgetmaster/;
    }

    location /budgetmaster/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /budgetmaster/index.html;
    }
}